name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PyTorch CPU wheels
        run: |
          python -m pip install --upgrade pip
          pip install --extra-index-url https://download.pytorch.org/whl/cpu torch torchvision

      - name: Install project
        run: pip install ".[dev]"

      - name: Lint & Test
        run: |
          pip install ruff black
          ruff check tinyvision tests
          pytest -q

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t tinyvision:ci .

      - name: Smoke test
        run: |
          docker run -d --rm -p 8000:8000 --name tinyvision tinyvision:ci
          sleep 10
          curl -f http://localhost:8000/health
          docker stop tinyvision
