name: CI (placeholder)

on:
  push:
  pull_request:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: |
          echo "GitHub Actions is working!"
          echo "TODO: add tests, build and Docker"
